version: "3"

services:
  mini_nvr_recorder_cam1:
    container_name: mini-nvr-recorder-cam1
    image: ameer1234567890/mini-nvr-recorder:latest
    environment:
      - TZ=Asia/Karachi
      - "NP_CCTV_URL=rtsp://rtsp:12345678@babycam.lan:554/av_stream/ch0"
    volumes:
      - /mnt/usb3/docker/mini-nvr/recordings/cam1:/data
    restart: unless-stopped

  mini_nvr_cleaner:
    container_name: mini-nvr-cleaner
    image: ameer1234567890/mini-nvr-cleaner:latest
    environment:
      - TZ=Asia/Karachi
      - "NP_MAX_FILE_AGE_HOURS=168"
    volumes:
      - /mnt/usb3/docker/mini-nvr/recordings:/data
      - /mnt/usb3/docker/mini-nvr/cleaner.py:/app/app.py:ro
    restart: unless-stopped

  mini_nvr_web:
    container_name: mini-nvr-web
    image: php:apache
    ports:
      - 26880:80
    environment:
      - "NP_CAM_cam1=BabyCam HD"
      - "NP_TITLE=Mini NVR"
      - "NP_FOOTER=Originally made by <i>BOZET Herwin</i> & improved by <i>Ameer Dawood</i>"
      - TZ=Asia/Karachi
    volumes:
      - /mnt/usb3/docker/mini-nvr/htdocs:/var/www/html
      - /mnt/usb3/docker/mini-nvr/apache2.conf:/etc/apache2/apache2.conf:ro
      - /mnt/usb3/docker/mini-nvr/recordings:/var/www/html/data:ro
    restart: unless-stopped
