name: Build Docker Container

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Docker Tag'
        required: true
        default: 'latest'
jobs:
  docker-recorder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ameer1234567890/mini-nvr-recorder
          tags: type=semver,pattern={{version}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
<<<<<<< HEAD
        uses: docker/build-push-action@v5
=======
        uses: docker/build-push-action@v7
>>>>>>> 1d24f09d17373e272a33ce1e1e57b2f51c8eae61
        with:
          file: ./Dockerfile_recorder
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.event.inputs.tags || steps.meta.outputs.tags }}
  docker-cleaner:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ameer1234567890/mini-nvr-cleaner
          tags: type=semver,pattern={{version}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
<<<<<<< HEAD
        uses: docker/build-push-action@v5
=======
        uses: docker/build-push-action@v7
>>>>>>> 1d24f09d17373e272a33ce1e1e57b2f51c8eae61
        with:
          file: ./Dockerfile_cleaner
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.event.inputs.tags || steps.meta.outputs.tags }}
